### ISSUE TITLE
在pr合并只允许"squash and merge“时没有必要产生“Rebase suggestions"

### ISSUE THREAD

**Issue by mingmingtsao** [qiniu/reviewbot#111]
rt

**Comment by CarlJi** [comment]
I believe these are two separate things here:

* "Squash and merge" gives the ability to handle non-standard commit histories to those who have merging privileges.
* "Rebase suggestions" provides suggestions to the person submitting the pull request to make their commit history more standard.

Personally, as an engineer, I lean towards making our work more standardized, which is the most important aspect.
