### ISSUE TITLE
Proposal: provide github action to do reviewbot image release

### ISSUE THREAD

**Issue by CarlJi** [qiniu/reviewbot#157]

**Comment by jimyag** [comment]
May need to push to docker hub.

**Comment by CarlJi** [comment]
> May need to push to docker hub.

Yes, it would be preferable to provide an official Docker image upon the release of Reviewbot.

**Comment by CarlJi** [comment]
It's better to also check the functionality of image when release.

**Comment by jimyag** [comment]
> > May need to push to docker hub.可能需要推送到 docker hub。
> 
> Yes, it would be preferable to provide an official Docker image upon the release of Reviewbot.

push to ghcr (GitHub Container Registry)
