### ISSUE TITLE
[staticcheck] Unable handle custom tag

### ISSUE THREAD

**Issue by CarlJi** [qiniu/reviewbot#24]
For example:

<img width="899" alt="image" src="https://github.com/qiniu/reviewbot/assets/10810759/22c81e5a-2e21-4976-9af7-244ecd497db3">

**Comment by yuyang0914** [comment]
fix: #88

**Comment by CarlJi** [comment]
tags rules from go-zero: https://go-zero.dev/en/docs/tutorials/go-zero/configuration/overview#tag-checksum-rule

**Comment by CarlJi** [comment]
The native [JSON library](https://pkg.go.dev/encoding/json) in Go only supports a few tags, such as `omitempty`. However, in reality, the industry has many customized use cases that have, to some extent, driven the iteration of the official library. Hence, [the v2 proposal exists](https://github.com/golang/go/discussions/63397).

For staticcheck, seems it's strategy is also iterated by incorporating various popular use cases([#540](https://github.com/dominikh/go-tools/issues/540),[#1266](https://github.com/dominikh/go-tools/pull/1266)). Therefore, the more appropriate approach for this issue seems to be for go-zero to submit a pull request (PR) to Staticcheck.

As a quick solution, `Reviewbot` can temporarily handle the adaptation by itself.
