### ISSUE TITLE
Proposal: Why not consider using LLM to do some review work?

### ISSUE THREAD

**Issue by yangchnet** [qiniu/reviewbot#47]
For example:
```go
package main

import "fmt"

func main() {
	i := 0
	go func() {
		for i < 10 {
			i += 1 // want i to be 10
		}
	}()

	// do another thing

	fmt.Println(i)
}
```

when I ask LLM: Is there something abnormal in this code?

LLM:
Yes, there is a race condition in this code. The variable i is accessed from two different goroutines: the main goroutine and the anonymous goroutine you created. Both are trying to modify i without any form of synchronization, which can lead to unpredictable behavior.

In Go, you can use primitives provided by the sync package, such as sync.WaitGroup and sync.Mutex, to avoid race conditions. Here's how you could modify your code:
```go
package main

import (
    "fmt"
    "sync"
)

func main() {
    var i int
    var wg sync.WaitGroup
    var mu sync.Mutex

    wg.Add(1)
    go func() {
        defer wg.Done()
        for {
            mu.Lock()
            if i >= 10 {
                mu.Unlock()
                break
            }
            i++
            mu.Unlock()
        }
    }()

    // do another thing

    wg.Wait()
    mu.Lock()
    fmt.Println(i)
    mu.Unlock()
}
```

In this example, we use sync.Mutex to protect access to i and sync.WaitGroup to ensure that the main goroutine waits for the anonymous goroutine to finish before accessing i.

**Comment by yangchnet** [comment]
@CarlJi Thank you for your reply.
I use github copilot daily to help me write code and check errors. I think copilot is fully qualified for this job. But I don’t know if github copilot can be called through open api, or we can use gpt4+prompt to achieve similar effects.

**Comment by CarlJi** [comment]
use #390 to track.
